# Generated by Django 5.2.3 on 2025-07-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=200)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('DOC', 'Docente'), ('EST', 'Estudiante')], default='EST', max_length=10)),
            ],
        ),
    ]
