# Generated by Django 5.2.3 on 2025-07-15 22:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=200)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('DOC', 'Docente'), ('EST', 'Estudiante')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('activo', models.BooleanField(default=True)),
                ('estudiantes', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'Estudiante'}, to='sgta.usuario')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgta.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='  ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.DateField()),
                ('tipo_tarea', models.CharField(choices=[('ACD', 'Aprendizaje en Contacto con el Docente'), ('AA', 'Aprendizaje Autónomo'), ('APE', 'Aprendizaje Práctico Experimental')], max_length=3)),
                ('es_grupal', models.BooleanField(default=False)),
                ('rubrica', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('grupos_asignados', models.ManyToManyField(blank=True, related_name='tareas_grupales', to='sgta.grupo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='sgta.usuario')),
                ('estudiantes_asignados', models.ManyToManyField(blank=True, related_name='tareas_recibidas', to='sgta.usuario')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
