# Generated by Django 5.2.3 on 2025-07-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ADM', 'Administrador'), ('DOC', 'Docente'), ('EST', 'Estudiante')], max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgta.asignatura')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, to='sgta.usuario')),
                ('estudiantes', models.ManyToManyField(limit_choices_to={'rol': 'EST'}, related_name='cursos_inscritos', to='sgta.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_tarea', models.CharField(choices=[('ACD', 'Actividad de Construcción del Conocimiento'), ('AA', 'Actividad de Aprendizaje'), ('APE', 'Actividad Práctica Específica')], max_length=3)),
                ('es_grupal', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('archivo_explicacion', models.FileField(blank=True, help_text='Archivo PDF con la explicación de la tarea', null=True, upload_to='explicaciones_tareas/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='sgta.curso')),
                ('creada_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOC'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgta.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgta.curso')),
                ('creado_por', models.ForeignKey(limit_choices_to={'rol': 'DOC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to='sgta.usuario')),
                ('estudiantes', models.ManyToManyField(limit_choices_to={'rol': 'EST'}, to='sgta.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgta.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgta.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregas/')),
                ('fecha_entregada', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='sgta.asignacion')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgta.grupo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tareas', to='sgta.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, help_text='Docente responsable de impartir la asignatura', limit_choices_to={'rol': 'DOC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_responsable', to='sgta.usuario'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='registrada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_registradas', to='sgta.usuario'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgta.asignatura')),
                ('periodo_lectivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgta.periodolectivo')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'EST'}, on_delete=django.db.models.deletion.CASCADE, to='sgta.usuario')),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura', 'periodo_lectivo')},
            },
        ),
    ]
