# Generated by Django 5.2.3 on 2025-07-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregatarea',
            options={'ordering': ['-fecha_entregada'], 'verbose_name': 'Entrega de tarea', 'verbose_name_plural': 'Entregas de tareas'},
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='fecha_retroalimentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='retroalimentacion_archivo',
            field=models.FileField(blank=True, help_text='Archivo PDF con retroalimentación detallada', null=True, upload_to='retroalimentaciones/'),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Comentarios de retroalimentación en texto'),
        ),
    ]
