# Generated by Django 5.2.3 on 2025-07-25 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgta.asignatura')),
                ('docente', models.ForeignKey(limit_choices_to={'is_docente': True}, on_delete=django.db.models.deletion.CASCADE, to='sgta.usuario')),
                ('estudiantes', models.ManyToManyField(limit_choices_to={'is_estudiante': True}, related_name='cursos_inscritos', to='sgta.usuario')),
            ],
        ),
    ]
