# Generated by Django 5.2.3 on 2025-07-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0002_create_asignatura_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, help_text='Docente responsable de impartir la asignatura', limit_choices_to={'rol': 'DOC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_responsable', to='sgta.usuario'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='registrada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_registradas', to='sgta.usuario'),
        ),
    ]
