# Generated by Django 5.2.3 on 2025-07-26 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0002_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='estudiantes_asignados',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='grupos_asignados',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='sgta.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgta.curso'),
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregas/')),
                ('fecha_entregada', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tareas', to='sgta.usuario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='sgta.asignacion')),
            ],
        ),
    ]
