# Generated by Django 5.2.3 on 2025-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0002_asignatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DOC', 'Docente'), ('EST', 'Estudiante')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='asignatura',
            table=None,
        ),
    ]
