# Generated by Django 5.2.3 on 2025-07-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
