# Generated by Django 5.2.3 on 2025-07-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0003_remove_asignacion_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, to='sgta.usuario'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(limit_choices_to={'rol': 'EST'}, related_name='cursos_inscritos', to='sgta.usuario'),
        ),
    ]
