# Generated by Django 5.2.3 on 2025-07-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0003_delete_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DOC', 'Docente'), ('EST', 'Estudiante')], default='EST', max_length=10),
        ),
    ]
