# Generated by Django 5.2.3 on 2025-07-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0003_add_docente_responsable_to_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
