# Generated by Django 5.2.3 on 2025-07-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0004_alter_curso_docente_alter_curso_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgta.grupo'),
        ),
    ]
