# Generated by Django 5.2.3 on 2025-07-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0004_make_email_unique'),
    ]

    operations = [
    ]
