# Generated by Django 5.2.3 on 2025-07-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgta', '0005_entregatarea_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='archivo_explicacion',
            field=models.FileField(blank=True, help_text='Archivo PDF con la explicación de la tarea', null=True, upload_to='explicaciones_tareas/'),
        ),
    ]
